### ISSUE TITLE
PKGMK_DOWNLOAD variable make trouble if set to "no"

### ISSUE THREAD

**Issue by tnut** [NuTyX/cards#4]
If the variable PKGMK_DOWNLOAD is set to "no" even with the option -d, pkgmk doens't want to download the source anymore

**Comment by tnut** [comment]
The prob is that pkgmk-conf is readed AFTER parsing arguments of pkgmk script. This is partially correct because we can specify an alternate config file as argument. This logic has to be smarter.

**Comment by peter1000** [comment]
In my opinion this is the correct behavior:  if the config says: `PKGMK_DOWNLOAD="no"` I would expect it to be: NO ;)

Anyway probably just a question of what one wants e.g: command-line options should always overwrite config settings. 

But you could probably  overwrite selected items: after reading the pkgmk-conf: did not really try it because I think if the config says no it's ok

```
parsing_arguments: contains: -d
read pkgmk-conf:  PKGMK_DOWNLOAD="no"

overwrite selected items: if parsing_arguments: contains: -d:  PKGMK_DOWNLOAD="yes"
```

**Comment by tnut** [comment]
Won't be fixed
